gdata=read.delim("gapminderDataFiveYear.txt")
str(gdata)
tail(gdata)
names(gdata)
colors=c("red"      ,      "green"   ,      "blue" )
plot(lifeExp ~  gdpPercap, gdata, col=colors)
attach(gdata)
hist(gdpPercap,col=colors)
levels(continent)
nlevels(continent)
str(continent)
plot=table(continent)
barplot(plot
plot_data=subset(gdata, subset=country!="Afganistan")
ggplot(plot_data) + geom_point(aes(x = pop, y = lifeExp))
ggplot(gdata) + geom_point(aes(x = pop, y = lifeExp))
ggplot(gdata) + geom_point(aes(pop,lifeExp))
qplot(pop,lifeExp, data = gdata)
